name: SVG to png Workflow

on:
  push:
    paths:
      - 'source/assets/svg-source/*.svg'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get added files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
          operation: 'added'
      - name: Run command on each file
        run: |
          IFS=',' read -a files <<< "${{ steps.files.outputs.all }}"
          for file in "${files[@]}"; do
            echo "Running command on $file"
            # Replace this with your command
            cat "$file"
          done
      # - uses: actions/checkout@v2
      # - name: Install ImageMagick
        # run: sudo apt-get install imagemagick
      # - uses: jitterbit/get-changed-files@v1
      #   with:
      #     format: 'svg'
      # - run: | mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}') for added_modified_file in "${added_modified_files[@]}"; do echo "Do something with this ${added_modified_file}." done
      # - name: Convert SVG to PNG
      #   run: convert -density 300 ${{ github.event.commits[0].added[0] }}.svg ${{ github.event.commits[0].added[0] }}.png
      # - name: Upload PNG as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: png-file
      #     path: ${{ github.event.head_commit.message }}.png
